repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8

  - repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
