dist: focal
language: python
python:
  - "3.8"
addons:
  apt:
    packages:
      - python3.8-dev
      - libxml2-dev
      - libxslt1-dev
      - libpng-dev
      - libfreetype6-dev
      - graphviz
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache: pip
install:
  - make virtualenv
  - ls -la ./env/bin/
  - make install-requirements download-corpora download-spacy-data-en
script: make test
after_script: cd ~
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
