name: main ci workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get install libxml2-dev libxslt1-dev libpng-dev libfreetype6-dev graphviz

    - name: Prepare env, install python dependencies
      run: |
        make virtualenv install-requirements download-corpora download-spacy-data-en

    - name: Test
      run: |
        make test
